# Generated by Django 4.2.7 on 2026-04-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_qb_per_user_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='qbsynclog',
            new_name='api_qbsyncl_user_id_cfc566_idx',
            old_name='api_qbsync_user_id_status_idx',
        ),
        migrations.RenameIndex(
            model_name='qbsynclog',
            new_name='api_qbsyncl_idempot_93cffa_idx',
            old_name='api_qbsync_idempot_idx',
        ),
        migrations.AlterField(
            model_name='qbaccount',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='qbglmapping',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='qbsynclog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
