# Generated by Django 4.2.7 on 2026-04-30 04:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_qbsync_index_polish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcontract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('vendor_name', models.CharField(max_length=255)),
                ('vendor_email', models.EmailField(blank=True, max_length=254)),
                ('vendor_phone', models.CharField(blank=True, max_length=30)),
                ('scope', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcontracts', to='api.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubcontractLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('csi_code', models.CharField(blank=True, max_length=20)),
                ('csi_title', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subcontract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='api.subcontract')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coverage_type', models.CharField(choices=[('general_liability', 'General Liability'), ('workers_comp', "Workers' Comp"), ('auto_liability', 'Auto Liability'), ('umbrella', 'Umbrella / Excess'), ('builders_risk', 'Builders Risk'), ('professional', 'Professional'), ('pollution', 'Pollution'), ('other', 'Other')], default='general_liability', max_length=30)),
                ('carrier', models.CharField(blank=True, max_length=255)),
                ('policy_number', models.CharField(blank=True, max_length=100)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('coverage_limit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('aggregate_limit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('additional_insured', models.BooleanField(default=False)),
                ('waiver_of_subrogation', models.BooleanField(default=False)),
                ('primary_and_non_contributory', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('last_reminder_sent', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subcontract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_certificates', to='api.subcontract')),
            ],
            options={
                'ordering': ['expiration_date', 'coverage_type'],
            },
        ),
        migrations.CreateModel(
            name='SubLineAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allocation_date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_line_allocations', to='api.invoice')),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='api.subcontractlineitem')),
                ('subcontract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='api.subcontract')),
            ],
            options={
                'ordering': ['-allocation_date'],
                'indexes': [models.Index(fields=['subcontract'], name='api_subline_subcont_27e746_idx'), models.Index(fields=['invoice'], name='api_subline_invoice_42122a_idx')],
            },
        ),
        migrations.CreateModel(
            name='LienWaiver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('waiver_type', models.CharField(choices=[('cond_partial', 'Conditional Partial'), ('uncond_partial', 'Unconditional Partial'), ('cond_final', 'Conditional Final'), ('uncond_final', 'Unconditional Final')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('signed', 'Signed'), ('void', 'Void')], default='draft', max_length=20)),
                ('claimant_name', models.CharField(help_text='The contractor/sub releasing lien rights', max_length=255)),
                ('customer_name', models.CharField(blank=True, help_text='Who the claimant is contracting with (often the GC)', max_length=255)),
                ('owner_name', models.CharField(blank=True, help_text='Property owner', max_length=255)),
                ('job_address', models.TextField(blank=True)),
                ('job_description', models.TextField(blank=True)),
                ('through_date', models.DateField(help_text='Waiver covers all work performed/payments received through this date')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount being released (paid or expected to be paid)', max_digits=14)),
                ('signed_by', models.CharField(blank=True, max_length=255)),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('notary_name', models.CharField(blank=True, help_text='For unconditional waivers that require notarization', max_length=255)),
                ('pdf_filename', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lien_waivers', to='api.project')),
                ('subcontract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lien_waivers', to='api.subcontract')),
            ],
            options={
                'ordering': ['-through_date', '-created_at'],
                'indexes': [models.Index(fields=['project', '-through_date'], name='api_lienwai_project_31731d_idx'), models.Index(fields=['subcontract'], name='api_lienwai_subcont_953ec0_idx'), models.Index(fields=['status'], name='api_lienwai_status_bac0f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_date', models.DateField()),
                ('weather', models.CharField(blank=True, max_length=255)),
                ('temp_high_f', models.CharField(blank=True, max_length=10)),
                ('temp_low_f', models.CharField(blank=True, max_length=10)),
                ('crew_size', models.IntegerField(default=0)),
                ('crew_notes', models.TextField(blank=True)),
                ('work_performed', models.TextField(blank=True)),
                ('materials_delivered', models.TextField(blank=True)),
                ('equipment_on_site', models.TextField(blank=True)),
                ('issues', models.TextField(blank=True)),
                ('visitors', models.TextField(blank=True)),
                ('photo_filenames', models.JSONField(blank=True, default=list)),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='api.project')),
            ],
            options={
                'ordering': ['-log_date'],
                'indexes': [models.Index(fields=['project', '-log_date'], name='api_dailylo_project_2040cf_idx')],
            },
        ),
    ]
