# Generated by Django 4.2.7 on 2026-04-30 16:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_multi_tenant_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerContract',
            fields=[
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='owner_contract', serialize=False, to='api.project')),
                ('contract_number', models.CharField(blank=True, max_length=100)),
                ('contract_type', models.CharField(blank=True, choices=[('lump_sum', 'Lump Sum / Fixed Price'), ('cost_plus', 'Cost Plus'), ('gmp', 'Guaranteed Maximum Price (GMP)'), ('time_and_mat', 'Time & Materials'), ('unit_price', 'Unit Price'), ('other', 'Other')], max_length=20)),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('owner_name', models.CharField(blank=True, help_text='Owner / client legal name', max_length=255)),
                ('owner_rep_name', models.CharField(blank=True, max_length=255)),
                ('owner_rep_email', models.EmailField(blank=True, max_length=254)),
                ('owner_rep_phone', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('attachment_filenames', models.JSONField(blank=True, default=list, help_text='Signed PDF, exhibits, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_number', models.IntegerField(help_text='1, 2, 3, ... per project')),
                ('application_date', models.DateField(blank=True, null=True)),
                ('period_from', models.DateField(blank=True, null=True)),
                ('period_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('retainage_percent', models.DecimalField(decimal_places=2, default=10, help_text='App-level default; lines can override', max_digits=5)),
                ('original_contract_sum', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_change_orders_at_submission', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_applications', to='api.project')),
            ],
            options={
                'ordering': ['-application_number'],
            },
        ),
        migrations.CreateModel(
            name='PayAppLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_number', models.CharField(blank=True, help_text='"1", "2.1", "CO-3", etc.', max_length=20)),
                ('csi_code', models.CharField(blank=True, max_length=20)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('scheduled_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('work_completed_from_previous', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('work_completed_this_period', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('materials_stored', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('retainage_percent_override', models.DecimalField(decimal_places=2, default=0, help_text='Per-line retainage override. Use 0 to inherit the app-level rate.', max_digits=5)),
                ('sort_order', models.IntegerField(default=0)),
                ('pay_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='api.paymentapplication')),
            ],
            options={
                'ordering': ['sort_order', 'item_number'],
            },
        ),
        migrations.CreateModel(
            name='SubcontractChangeOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('justification', models.TextField(blank=True)),
                ('requested_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('requested_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=255)),
                ('rejected_reason', models.TextField(blank=True)),
                ('photo_filenames', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subcontract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_orders', to='api.subcontract')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subcontract', 'status'], name='api_subcont_subcont_8da89c_idx')],
            },
        ),
        migrations.CreateModel(
            name='PrimeChangeOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(blank=True, help_text='"PCO-001", "CO-12", whatever the GC uses', max_length=50)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('justification', models.TextField(blank=True, help_text='Why the change is needed')),
                ('requested_amount', models.DecimalField(decimal_places=2, default=0, help_text='Can be negative for credits', max_digits=14)),
                ('requested_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0, help_text='May differ from requested', max_digits=14)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, help_text='Owner rep / signer name', max_length=255)),
                ('rejected_reason', models.TextField(blank=True)),
                ('photo_filenames', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prime_change_orders', to='api.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='api_primech_project_44663c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='paymentapplication',
            index=models.Index(fields=['project', '-application_number'], name='api_payment_project_7ab3b5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentapplication',
            unique_together={('project', 'application_number')},
        ),
    ]
