# Generated by Django 4.2.7 on 2026-04-30 17:04

from django.db import migrations, models


def grandfather_existing_companies(apps, schema_editor):
    """Companies that exist before this migration ran (Marlene's internal
    admin account, any test fixtures) get marked 'active' so they aren't
    locked out by HasActiveSubscription. New signups go through the trial
    flow in api.auth_views.register."""
    Company = apps.get_model('api', 'Company')
    Company.objects.all().update(subscription_status='active')


def reverse_noop(apps, schema_editor):
    """Reversing the data migration is a no-op — we don't try to undo the
    grandfathering, just allow the schema to come back."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_change_orders_and_pay_apps'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='current_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='company',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_status',
            field=models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('none', 'None')], default='trialing', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_tier',
            field=models.CharField(blank=True, choices=[('starter', 'Starter'), ('pro', 'Pro'), ('scale', 'Scale')], max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(grandfather_existing_companies, reverse_noop),
    ]
