# Generated by Django 4.2.7 on 2026-04-30 19:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_change_orders_and_pay_apps'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('color_hex', models.CharField(blank=True, help_text='Optional UI tint, e.g. "#1F6FEB"', max_length=9)),
                ('started_at', models.DateField(blank=True, null=True)),
                ('finished_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='api.project')),
            ],
            options={
                'ordering': ['project', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('punch', 'Punchlist'), ('inspection', 'Inspection'), ('materials', 'Materials'), ('office', 'Office'), ('subcontractor', 'Subcontractor'), ('other', 'Other')], default='other', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('needs_verification', 'Needs Verification'), ('done', 'Done'), ('wont_fix', "Won't Fix")], default='open', max_length=20)),
                ('assigned_to_name', models.CharField(blank=True, max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('recurrence', models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], default='none', max_length=10)),
                ('reminder_days_before', models.IntegerField(default=0)),
                ('last_reminder_sent', models.DateTimeField(blank=True, null=True)),
                ('photo_filenames', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='api.teammember')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='api.projectphase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskHandoff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_name', models.CharField(blank=True, max_length=255)),
                ('to_name', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handoffs_sent', to='api.teammember')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoffs', to='api.projecttask')),
                ('to_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handoffs_received', to='api.teammember')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_comments', to='api.teammember')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.projecttask')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('is_done', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='api.projecttask')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('csi_code', models.CharField(blank=True, help_text='e.g. "03 30 00"', max_length=20)),
                ('csi_title', models.CharField(blank=True, help_text='CSI MasterFormat title', max_length=255)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('budgeted_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_line_items', to='api.project')),
            ],
            options={
                'ordering': ['project', 'sort_order', 'csi_code'],
            },
        ),
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('csi_code', models.CharField(blank=True, help_text='Snapshot of line item CSI at allocation time', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('allocation_date', models.DateField(default=datetime.date.today)),
                ('qb_pushed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_allocations', to='api.invoice')),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='api.budgetlineitem')),
            ],
            options={
                'ordering': ['-allocation_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskWatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='api.projecttask')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watching_tasks', to='api.teammember')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('task', 'team_member')},
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Template label, shown in the picker', max_length=255)),
                ('title', models.CharField(help_text='Default ProjectTask.title', max_length=255)),
                ('details', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('punch', 'Punchlist'), ('inspection', 'Inspection'), ('materials', 'Materials'), ('office', 'Office'), ('subcontractor', 'Subcontractor'), ('other', 'Other')], default='other', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('subtask_titles', models.JSONField(blank=True, default=list, help_text='List[str] — one Subtask per title')),
                ('recurrence', models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], default='none', max_length=10)),
                ('reminder_days_before', models.IntegerField(default=0)),
                ('default_assignee_name', models.CharField(blank=True, max_length=255)),
                ('default_phase_name', models.CharField(blank=True, help_text='Phase name (resolved per-project at spawn time)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='api.company')),
                ('default_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_templates', to='api.teammember')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('task', 'Gantt Task'), ('milestone', 'Milestone'), ('look_ahead', 'Look-Ahead'), ('submittal', 'Submittal'), ('rfi', 'RFI')], default='task', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('percent_complete', models.IntegerField(default=0)),
                ('assigned_to_name', models.CharField(blank=True, help_text='Snapshot of assignee name at assignment time', max_length=255)),
                ('trade', models.CharField(blank=True, help_text='"Electrical", "Plumbing" — used by look-ahead grouping', max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('spec_section', models.CharField(blank=True, help_text='CSI section, e.g. "07 21 13 — Insulation"', max_length=100)),
                ('submitted_date', models.DateField(blank=True, null=True)),
                ('required_by_date', models.DateField(blank=True, null=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('open', 'Open'), ('submitted', 'Submitted'), ('revise_resubmit', 'Revise & Resubmit'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('answered', 'Answered')], default='open', max_length=20)),
                ('rfi_number', models.CharField(blank=True, max_length=50)),
                ('question', models.TextField(blank=True)),
                ('answer', models.TextField(blank=True)),
                ('responded_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_items', to='api.teammember')),
                ('depends_on', models.ManyToManyField(blank=True, related_name='dependents', to='api.scheduleitem')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_items', to='api.projectphase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to='api.project')),
            ],
            options={
                'ordering': ['project', 'start_date', 'created_at'],
                'indexes': [models.Index(fields=['project', 'kind'], name='api_schedul_project_676fba_idx'), models.Index(fields=['project', 'start_date'], name='api_schedul_project_5b9573_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['project', 'status'], name='api_project_project_eb4b0d_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['assigned_to', 'status'], name='api_project_assigne_29f128_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectphase',
            unique_together={('project', 'name')},
        ),
        migrations.AddIndex(
            model_name='budgetlineitem',
            index=models.Index(fields=['project', 'csi_code'], name='api_budgetl_project_72a830_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetallocation',
            index=models.Index(fields=['invoice'], name='api_budgeta_invoice_42d31e_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetallocation',
            index=models.Index(fields=['line_item'], name='api_budgeta_line_it_d09188_idx'),
        ),
    ]
