# Generated by Django 4.2.7 on 2026-05-01 01:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_a1_6_tasks_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='qb_last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last successful QBSyncLog row for this Company.', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='qb_mode',
            field=models.CharField(blank=True, choices=[('qbo', 'QuickBooks Online (REST API)'), ('qbwc', 'QuickBooks Desktop (Web Connector polled SOAP)'), ('', 'Not connected')], default='', help_text='Drives QBService factory dispatch.', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='qbwc_password',
            field=models.CharField(blank=True, help_text='Shared secret for QB Web Connector authentication.', max_length=64),
        ),
        migrations.AddField(
            model_name='subcontract',
            name='is_1099_vendor',
            field=models.BooleanField(default=False, help_text='Pay this vendor on a 1099 (mirrors QB Vendor.Vendor1099).'),
        ),
        migrations.AddField(
            model_name='subcontract',
            name='vendor_tax_id',
            field=models.CharField(blank=True, help_text='EIN or SSN, for 1099-NEC reporting. Stored as-is; surface masked in UI.', max_length=20),
        ),
        migrations.CreateModel(
            name='QBLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contractorhub_entity_type', models.CharField(help_text='e.g. "Subcontract", "Project", "Invoice".', max_length=50)),
                ('contractorhub_entity_id', models.CharField(help_text='UUID or int as string — whatever the source entity uses.', max_length=64)),
                ('qb_entity_type', models.CharField(help_text='e.g. "Vendor", "Customer", "Bill", "Invoice", "BillPayment".', max_length=50)),
                ('qb_entity_id', models.CharField(blank=True, help_text='Empty until first successful sync. Populated from QB response.', max_length=64)),
                ('qb_sync_token', models.CharField(blank=True, help_text="QBO's optimistic-lock SyncToken; QBWC's EditSequence. Updated on every successful write.", max_length=20)),
                ('sync_state', models.CharField(choices=[('synced', 'Synced'), ('queued', 'Queued (waiting for QBWC poll or retry)'), ('failed_permanent', 'Failed permanently')], default='queued', max_length=20)),
                ('failure_reason', models.TextField(blank=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qb_links', to='api.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'sync_state'], name='api_qblink_company_5d0548_idx'), models.Index(fields=['company', 'qb_entity_type', 'qb_entity_id'], name='api_qblink_company_9b2389_idx')],
                'unique_together': {('company', 'contractorhub_entity_type', 'contractorhub_entity_id')},
            },
        ),
    ]
