# Generated by Django 4.2.7 on 2026-05-01 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_billing_fields'),
        ('api', '0008_qb_v2_foundation'),
    ]

    operations = [
    ]
