# Generated by Django 4.2.7 on 2026-05-01 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_qb_v2_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='default_qb_expense_account_id',
            field=models.CharField(blank=True, help_text='QB Account.Id used as the default expense GL when posting vendor Bills.', max_length=64),
        ),
        migrations.AddField(
            model_name='company',
            name='default_qb_payment_account_id',
            field=models.CharField(blank=True, help_text='QB Account.Id (Bank/Credit Card) used as the default for BillPayments.', max_length=64),
        ),
        migrations.AddField(
            model_name='invoice',
            name='kind',
            field=models.CharField(choices=[('client_invoice', 'Client invoice (we send → QB Invoice)'), ('vendor_bill', 'Vendor bill (we receive → QB Bill)')], default='client_invoice', help_text='client_invoice (default; sent to client) vs vendor_bill (received from sub).', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subcontract',
            field=models.ForeignKey(blank=True, help_text="When kind=='vendor_bill', the Subcontract this bill is from. Used to resolve the QB Vendor.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_bills', to='api.subcontract'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vendor_invoice_number',
            field=models.CharField(blank=True, help_text="When kind=='vendor_bill', the vendor's own invoice number (becomes QB Bill DocNumber).", max_length=100),
        ),
    ]
