# Generated by Django 4.2.7 on 2026-05-01 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_qb_v2_vendor_bill'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='qblink',
            unique_together={('company', 'contractorhub_entity_type', 'contractorhub_entity_id', 'qb_entity_type')},
        ),
    ]
