# Generated by Django 4.2.7 on 2026-05-05 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_backfill_vendors_from_subcontracts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='qb_access_token',
        ),
        migrations.RemoveField(
            model_name='company',
            name='qb_realm_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='qb_refresh_token',
        ),
        migrations.RemoveField(
            model_name='company',
            name='qb_token_expires_at',
        ),
        migrations.AlterField(
            model_name='qbaccount',
            name='connected_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
