# Generated by Django 4.2.7 on 2026-05-07 17:36
#
# Encrypt existing QBAccount.access_token + refresh_token at rest. The
# AlterField ops are no-ops at the DB level (both old and new fields
# are TEXT columns) — the real work is in encrypt_existing_tokens, which
# loads each row, reads the still-plaintext token (EncryptedTextField's
# from_db_value falls through to raw bytes when decryption fails, which
# it always will on legacy plaintext rows), then saves it back so
# get_prep_value encrypts before the UPDATE statement.
#
# Reverse migration decrypts back to plaintext via the same trick.

import api.fields
from django.db import migrations


def encrypt_existing_tokens(apps, schema_editor):
    QBAccount = apps.get_model('api', 'QBAccount')
    # historical model; force re-save so EncryptedTextField.get_prep_value
    # runs and encrypts the values.
    for qa in QBAccount.objects.all():
        qa.save(update_fields=['access_token', 'refresh_token'])


def decrypt_existing_tokens(apps, schema_editor):
    """Reverse: read decrypted plaintext (via from_db_value), then
    when the field reverts to plain TextField in the prior migration,
    the values are already plaintext and stay that way."""
    QBAccount = apps.get_model('api', 'QBAccount')
    # Load each, reassign to force a fresh save with plaintext values.
    for qa in QBAccount.objects.all():
        qa.save(update_fields=['access_token', 'refresh_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_drop_company_qb_legacy_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qbaccount',
            name='access_token',
            field=api.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='qbaccount',
            name='refresh_token',
            field=api.fields.EncryptedTextField(),
        ),
        migrations.RunPython(encrypt_existing_tokens, decrypt_existing_tokens),
    ]
