# Generated by Django 4.2.7 on 2026-05-07 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_encrypt_qb_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('status_change', 'Status changed'), ('login', 'Logged in'), ('login_failed', 'Login failed'), ('signup', 'Signed up'), ('qb_connect', 'Connected QuickBooks'), ('qb_disconnect', 'Disconnected QuickBooks'), ('subscription_start', 'Subscription started'), ('subscription_cancel', 'Subscription canceled'), ('payment_failed', 'Payment failed')], max_length=30)),
                ('entity_type', models.CharField(blank=True, help_text='e.g. "LienWaiver", "PaymentApplication". Blank for non-entity events like login.', max_length=50)),
                ('entity_id', models.CharField(blank=True, help_text='UUID or int as string.', max_length=100)),
                ('before', models.JSONField(blank=True, help_text='Snapshot of relevant fields before the action (for update/status_change).', null=True)),
                ('after', models.JSONField(blank=True, help_text='Snapshot of relevant fields after the action.', null=True)),
                ('ip', models.GenericIPAddressField(blank=True, help_text='Captured for view-level events only.', null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Free-form per-action data (e.g. failed login email, Stripe event ID).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, help_text='Null for events with no company yet (e.g. failed login attempt for an email that does not exist).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='api.company')),
                ('user', models.ForeignKey(blank=True, help_text='The actor — who did this. Null for anonymous events.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_as_actor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', '-created_at'], name='api_auditlo_company_13e83d_idx'), models.Index(fields=['entity_type', 'entity_id'], name='api_auditlo_entity__ad4253_idx'), models.Index(fields=['user', '-created_at'], name='api_auditlo_user_id_47a824_idx')],
            },
        ),
    ]
