# Generated by Django 4.2.7 on 2026-05-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_audit_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='lienwaiver',
            name='check_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='lienwaiver',
            name='check_bank',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lienwaiver',
            name='check_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lienwaiver',
            name='check_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='lienwaiver',
            name='conditional_on_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lienwaiver',
            name='state',
            field=models.CharField(blank=True, choices=[('FL', 'Florida'), ('CA', 'California'), ('TX', 'Texas'), ('NY', 'New York'), ('', 'Generic (no state-specific form)')], default='', help_text='Drives which statutory PDF template renders. FL = §713.20.', max_length=2),
        ),
    ]
